module Stop_Watch(
    input  wire       M_r,          // Mode button (Split / Clear)
    input  wire       S_r,          // Start / Stop button
    input  wire       CLK,          // System clock
    input  wire       RST,          // Active low reset
    input  wire [1:0] Enable,       // Enable signal from main controller

    output reg  [3:0] m_1,          // Minutes tens
    output reg  [3:0] m_0,          // Minutes units
    output reg  [3:0] s_1,          // Seconds tens
    output reg  [3:0] s_0,          // Seconds units

    output reg        Stop_watch_end // high only if we at Clear state an enable == 2'b10 
);

////////////////////////////////////////////////////////////////////////////////////////////////////////
// Internal Signals 
////////////////////////////////////////////////////////////////////////////////////////////////////////

// Internal counters for minutes and seconds
reg [5:0] mm_I ;
reg [5:0] ss_I ;

// Registers to save time when split is pressed
reg [5:0] mm_split ;
reg [5:0] ss_split ;

// Control signals generated by FSM
reg      Int_En;   // Enables the counter
reg      Mux_out;  // Selects between normal time and split time


////////////////////////////////////////////////////////////////////////////////////////////////////////
// FSM Logic
////////////////////////////////////////////////////////////////////////////////////////////////////////

// FSM States encoding
localparam  [2:0]   Clear       = 3'b000, // Reset state
                    ON          = 3'b001, // Stopwatch running
                    STOP        = 3'b011, // Stopwatch stopped
                    Split_ON    = 3'b111, // Split while running
                    Split_STOP  = 3'b110; // Split while stopped

reg [2:0] current_state, next_state ; 


// FSM state register
always @(posedge CLK or negedge RST) begin
    if(!RST)
        current_state <= Clear ;
    else if (Enable == 2'b10)
        current_state <= next_state ;
end


// Next State transition logic (combinational)
always @(*) begin
    case (current_state)
        Clear: 
            begin
                if (S_r)       next_state = ON ;
                else           next_state = Clear ;   
            end    

        ON:
            begin
                if (S_r)       next_state = STOP ;
                else if (M_r)  next_state = Split_ON ;
                else           next_state = ON ; 
            end

        STOP:
            begin
                if (S_r)       next_state = ON ;
                else if (M_r)  next_state = Clear ;
                else           next_state = STOP ; 
            end


        Split_ON:
            begin
                if (S_r)       next_state = Split_STOP ;
                else if (M_r)  next_state = ON ;
                else           next_state = Split_ON ; 
            end

        Split_STOP:
            begin
                if (S_r)       next_state = Split_ON ;
                else if (M_r)  next_state = STOP ;
                else           next_state = Split_STOP ; 
            end
    endcase
end



// Output logic (Mealy: outputs depend on (current state & Input) )
always @(*) begin
    Int_En  = 1'b0 ;
    Mux_out = 1'b0 ; 
    Stop_watch_end  = 1'b0 ;
    
    case (current_state)
        Clear: //0
            begin
                Mux_out = 1'b0 ;
                if (Enable=='b10) Stop_watch_end  = 1'b1 ;
                if (S_r)  Int_En  = 1'b1 ; 
                else      Int_En  = 1'b0 ;
            end    

        ON://1
            begin
                Mux_out = 1'b0 ;
                if (S_r)  Int_En  = 1'b0 ; 
                else      Int_En  = 1'b1 ;
            end

        STOP://3
            begin
                Mux_out = 1'b0 ;
                if (S_r)  Int_En  = 1'b1 ; 
                else      Int_En  = 1'b0 ;
            end


        Split_ON:
            begin
                Mux_out = 1'b1 ;
                if (S_r)  Int_En  = 1'b0 ; 
                else      Int_En  = 1'b1 ;  
            end

        Split_STOP:
            begin
                Mux_out = 1'b1 ;
                if (S_r)  Int_En  = 1'b1 ; 
                else      Int_En  = 1'b0 ;
            end
    endcase
end


// =======================================================================
// Sequential logic To store Time at split case 
// =======================================================================
always @(posedge CLK or negedge RST) begin
    if (!RST) begin
        mm_I <= mm_I;
        ss_I <= ss_I;

        mm_split <= 'b0;
        ss_split <= 'b0;
    end

    else begin 
        case (current_state)

        Clear : 
            begin
                mm_I <= 'b0;
                ss_I <= 'b0;

                mm_split <= 'b0;
                ss_split <= 'b0;
            end 

        ON:
            begin
                if (M_r)  begin 
                    mm_split <= mm_I;
                    ss_split <= ss_I;
                end    
            end 

        STOP:
            begin
                mm_split <= 'b0;
                ss_split <= 'b0;

                if (M_r)  begin 
                    mm_I <= 'b0;
                    ss_I <= 'b0;
                end    
            end         

        Split_ON:
            begin
                mm_split <= mm_split;
                ss_split <= ss_split;
            end 

        Split_STOP:
            begin
                mm_split <= mm_split;
                ss_split <= ss_split;
            end
                    
        default :
            begin
                mm_I <= mm_I;
                ss_I <= ss_I;

                mm_split <= 'b0;
                ss_split <= 'b0;
            end    
        endcase
    end
end



////////////////////////////////////////////////////////////////////////////////////////////////////////
// Output logic (convert from binary to BCD-like digits)
////////////////////////////////////////////////////////////////////////////////////////////////////////
always @(*) begin
    case (Mux_out)

        0: begin
            // Display normal stopwatch time
            m_1 = mm_I / 10;
            m_0 = mm_I % 10;
            s_1 = ss_I / 10;
            s_0 = ss_I % 10;
        end

        1: begin
            // Display stored split time
            m_1 = mm_split / 10;
            m_0 = mm_split % 10;
            s_1 = ss_split / 10;
            s_0 = ss_split % 10;
        end
    endcase
end

////////////////////////////////////////////////////////////////////////////////////////////////////////
// Counter Logic (minutes and seconds)
////////////////////////////////////////////////////////////////////////////////////////////////////////
always @(posedge CLK or negedge RST) begin
    if (!RST) begin
        mm_I <= 0;
        ss_I <= 0;
    end
    else if (Int_En) begin
        // Increment seconds
        if (ss_I < 59)
            ss_I <= ss_I + 1;
        else begin
            ss_I <= 0;
            // Increment minutes
            if (mm_I < 59)
                mm_I <= mm_I + 1;
            else
                mm_I <= 0;
        end
    end
end

endmodule